/**
 * Schema exports for Weather API
 */

// OpenWeather API response schemas (for validating external API responses)
export {
  CoordSchema,
  WeatherConditionSchema,
  MainWeatherSchema,
  WindSchema,
  CloudsSchema,
  RainSchema,
  SnowSchema,
  SysSchema,
  OpenWeatherCurrentWeatherResponseSchema,
  OpenWeatherFiveDayForecastResponseSchema,
  GeocodingResultSchema,
  GeocodingResponseSchema,
  OpenWeatherErrorSchema,
  type Coord,
  type WeatherCondition,
  type MainWeather,
  type Wind,
  type Clouds,
  type Rain,
  type Snow,
  type Sys,
  type OpenWeatherCurrentWeatherResponse,
  type OpenWeatherFiveDayForecastResponse,
  type GeocodingResult,
  type GeocodingResponse,
  type OpenWeatherError,
} from "./openweather.schema";

// Public API schemas (for OpenAPI documentation)
export {
  CurrentWeatherQuerySchema,
  FiveDayForecastQuerySchema,
  CoordinatesResponseSchema,
  WeatherConditionResponseSchema,
  TemperatureResponseSchema,
  WindResponseSchema,
  AtmosphereResponseSchema,
  LocationResponseSchema,
  RainVolumeSchema,
  SnowVolumeSchema,
  PrecipitationResponseSchema,
  CurrentWeatherResponseSchema,
  FiveDayForecastResponseSchema,
  ErrorDetailsSchema,
  ErrorResponseSchema,
  RateLimitErrorDetailsSchema,
  RateLimitErrorSchema,
  HealthCheckResponseSchema,
  type CurrentWeatherQuery,
  type FiveDayForecastQuery,
  type CoordinatesResponse,
  type WeatherConditionResponse,
  type TemperatureResponse,
  type WindResponse,
  type AtmosphereResponse,
  type LocationResponse,
  type RainVolume,
  type SnowVolume,
  type PrecipitationResponse,
  type CurrentWeatherResponse,
  type FiveDayForecastResponse,
  type ErrorDetails,
  type ErrorResponse,
  type RateLimitErrorDetails,
  type RateLimitError,
  type HealthCheckResponse,
} from "./weather.schema";

// AI API schemas (for OpenAPI documentation)
export { AIQuerySchema, type AIQuery } from "./ai.schema";
