/**
 * Schema exports for Weather API
 */

// OpenWeather API response schemas (for validating external API responses)
export {
  CoordSchema,
  WeatherConditionSchema,
  MainWeatherSchema,
  WindSchema,
  CloudsSchema,
  RainSchema,
  SnowSchema,
  SysSchema,
  OpenWeatherCurrentResponseSchema,
  GeocodingResultSchema,
  GeocodingResponseSchema,
  OpenWeatherErrorSchema,
  type Coord,
  type WeatherCondition,
  type MainWeather,
  type Wind,
  type Clouds,
  type Rain,
  type Snow,
  type Sys,
  type OpenWeatherCurrentResponse,
  type GeocodingResult,
  type GeocodingResponse,
  type OpenWeatherError,
} from "./openweather.schema";

// Public API schemas (for OpenAPI documentation)
export {
  WeatherQuerySchema,
  CoordinatesResponseSchema,
  WeatherConditionResponseSchema,
  TemperatureResponseSchema,
  WindResponseSchema,
  AtmosphereResponseSchema,
  LocationResponseSchema,
  RainVolumeSchema,
  SnowVolumeSchema,
  PrecipitationResponseSchema,
  CurrentWeatherResponseSchema,
  ErrorDetailsSchema,
  ErrorResponseSchema,
  RateLimitErrorDetailsSchema,
  RateLimitErrorSchema,
  HealthCheckResponseSchema,
  type WeatherQuery,
  type CoordinatesResponse,
  type WeatherConditionResponse,
  type TemperatureResponse,
  type WindResponse,
  type AtmosphereResponse,
  type LocationResponse,
  type RainVolume,
  type SnowVolume,
  type PrecipitationResponse,
  type CurrentWeatherResponse,
  type ErrorDetails,
  type ErrorResponse,
  type RateLimitErrorDetails,
  type RateLimitError,
  type HealthCheckResponse,
} from "./weather.schema";
